### ISSUE TITLE
Remove promise anti-pattern

### ISSUE THREAD

**Issue by jfriend00** [mobily-enterprises/spa-fetch#1]
This code:

```
  return new Promise((resolve, reject) => {
    fetchPromise.then(
      response => {
        const responseClone = response.clone()
        resolve(responseClone)
      },
      error => {
        reject(error)
      }
    )
  })
```

is a promise anti-pattern.  Here you should not be wrapping an existing promise in another manually created one.

Instead, just do this:

```
    return fetchPromise.then(response => {
        return response.clone();
    });
```

**Comment by mercmobily** [comment]
Thank you for your ticket!

I suck at promises -- I always did.
What about the error? I really need the promise returned to be the same as what `fetch()` returns. If the network is down, `fetch()` will throw.
(I need to add a test for that actually... I forgot to do that)

**Comment by jfriend00** [comment]
Returning the promise directly as I suggested lets the caller see the rejection no different than your `reject(error)` that you already had, but with less code and with less opportunity to make mistakes.

**Comment by mercmobily** [comment]
...and you are right. I wrote more tests to see if the network error is cached -- and it is.

Right now the code reads:

      if (cachedItem && cachedItem.expires >= now) {
        return cachedItem.fetchPromise.then(response => response.clone())
      }

And

    return fetchPromise.then(response => response.clone())

Can I ask you to be so kind and tell me why it all works?
My understanding is that `cachedItem.fetchPromise.then(func)` will add `func` to the list of listeners to run when `fetchPromise` is resolved. I am aware that `then()` can be called at any point, before resolution, or after resolution.

What I am not 100% clear about is errors. My understanding of `then()` is that it accepts two functions, one if the promise succeeds, and one if there is an error. In this case, we are only passing the first one -- if the promise succeeds.

I am assuming that if there is an error, AND no error function is specified, then the error is propagated up to the original caller... is that right?
(I am sorry, I am very obsessive about understanding what is going on, and hate it when things are cloudy...)

Thanks for the report. I am adding a fix now.

**Comment by mercmobily** [comment]
BTW where did you find this? This is a small piece of a much bigger picture -- I am slowly releasing all of the parts in the coming 2/3 months. I didn't expect an issue open so quick :D

**Comment by jfriend00** [comment]
It looks like you figured out how I found it from your stackoverflow comment.  Posting a link on stackoverflow is making it public and inviting eyeballs to look <grin>.

`return fetchPromise.then(response => response.clone())` will work like this:

1. Register a `.then()` handler on fetchPromise with only a resolve handler.
2. Return the new promise that `fetchPromise.then()` creates.
3. Then, if `fetchPromise` resolves, it will call your arrow function and will make `response.clone()` be the resolved value of the promise that was previously returned.
4. Then, if `fetchPromise` rejects, the promise that has already been returned will reject also (as it's chained to follow `fetchPromise`).  So, when it resolves, the caller sees the result of `response.clone()` as the resolved value.  When it rejects, the caller sees the precise rejection that `fetchPromise` had.  The caller gets the two possible results you want.

**Comment by mercmobily** [comment]
Bonus question (this is getting ridiculous, I know...) If I HAD defined an error function in the `then()`:

     return fetchPromise.then(response => response.clone(), error => { console.log(error); return 'didn't work' })

Would the caller NOT receive an error as result, but the string 'didn't work' instead?
And if I wanted to do something AND then return the error, could have I done this:

     return fetchPromise.then(response => response.clone(), error => { console.log(error); return error })

...? Have I understood this right after -- what -- 8 years?

**Comment by jfriend00** [comment]
In the scenario where you are doing:

`return fetchPromise.then(response => response.clone())`

if you don't define an error handler for the promise then the caller gets the original rejection unmodified.

If you DO define an error handler, then the caller gets the result of running that error handler.  If you do anything in that error handler other than return a rejected promise or throw an exception, then the promise becomes resolved with the return value of your error handler as the resolved value and the caller sees the promise as resolved (the error has been eaten).   If you throw or return a rejected promise from your error handler, then that becomes the new error that the caller will see.

It's identical in concept to `try/catch` for synchronous exceptions.  With no `try/catch`, the caller gets the exception directly.  If you do have a try/catch handler, the caller gets the result of the catch block.  You either throw from the catch block so the caller gets an error (either same error or different error) or you don't throw and code continues as if there was no exception because you've "handled" the exception and execution continues as if the exception no longer exists.
